name: README build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
  
      - uses: actions/setup-node@v1
        with:
          node-version: '18.15'

      - uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Generate README file
        run: node src/index.js

      - name: Deploy to Gist
        uses: exuanbo/actions-deploy-gist@v1.1.4
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: serapagranchose/bc9b8dd8959b352699aa258a7924b729
          file_path: src/assets/resume.json
          gist_file_name: resume.json
          file_type: binary

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 📝 Update serapagranchose.json & README.md
