name: README build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
  
      - uses: actions/setup-node@v1
        with:
          node-version: '18.15'

      - uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Generate README file
        run: node src/index.js

      - name: Sync to Gist
        uses: Popsiclestick/gist-sync-action@v1.2.0
        with:
          auth: ${{ secrets.TOKEN }}
          gist_url: https://gist.github.com/serapagranchose/bc9b8dd8959b352699aa258a7924b729
          gist_title: resume.json
          gist_description: Example Gist Description
          github_file: src/assets/resume.json

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 📝 Update serapagranchose.json & README.md
